--Báo cáo 1ab 
WITH ac as
	(SELECT 
		DATE_COB
		, AMOUNT_LCY AS CREDIT_AMOUNT
		, TRANSACTION_NO
		, substr(TRANSACTION_NO, 1, instr(TRANSACTION_NO, '\') -1) AS CREDIT_TRANS --'
		, T_VALUE_DATE
		, T_DATE_TIME
		, PRODUCT_CATEGORY
		, AC_KEY 
		, CRF_TP
		FROM TCIMPORT.FACT_ACCT_ENTRY ac 
		WHERE
			ac.CUSTOMER_ID IS NOT NULL 
			AND ac.CRF_TP = 'CREDIT'
			AND ac.AMOUNT_LCY > 0
			AND ((ac.PRODUCT_CATEGORY BETWEEN 1001 AND 1099) AND ac.PRODUCT_CATEGORY <> 1008)
			AND (ac.DATE_COB = trunc(sysdate-1/*ALTER-1*/))
			AND ac.GL_NUMBER LIKE '42%')
--
, ft as
(SELECT 
	REGEXP_SUBSTR(FT_NO,'[^;]+',1,1) FT_NO
	, MERCHANT_ID 
	FROM TCIMPORT.FACT_FUND_TRANS ft
		WHERE 
			ft.DATE_COB = trunc(sysdate-1/*ALTER-1*/))
, dp AS 
(SELECT 
	ACCOUNT
	, REGISTER_DATE
	, PARTNER_NAME
	, ADDRESS
	, PARTNER_ID
	, PHONE 
	, CIF
	, ACCOUNT_OPEN_DATE
	FROM TCIMPORT.DIM_PARTNER dp 
	WHERE 
		dp.PARTNER_ID LIKE 'SPC%' 
		AND (trunc(sysdate-1/*ALTER-1*/) BETWEEN dp.EFF_FM_DT AND dp.EFF_TO_DT)
		AND dp.REGISTER_DATE <= trunc(sysdate-1/*ALTER-1*/))
, de AS 
(SELECT 
	* 
	FROM TCIMPORT.DIM_DEPOSIT de 
		WHERE 
		(trunc(sysdate-1/*ALTER-1*/) BETWEEN EFF_FROM_DATE  AND nvl(EFF_TO_DATE,TO_DATE(24000101,'yyyymmdd'))))
, dc AS 
(SELECT 
	* 
	FROM TCIMPORT.DIM_CUSTOMER dc 
		WHERE 
		(trunc(sysdate-1/*ALTER-1*/) BETWEEN EFF_FROM_DATE  AND nvl(EFF_TO_DATE,TO_DATE(24000101,'yyyymmdd'))))
SELECT 
	trunc(sysdate/*ALTER*/) AS DATA_DATE
	, dp.CIF AS CIF 
	, dc.CUSTOMER_NAME AS FULL_NAME
	, dp.ACCOUNT AS ACCOUNT_NUMBER
	, dp.ACCOUNT_OPEN_DATE AS ACCOUNT_OPEN_DATE
	, ac.PRODUCT_CATEGORY AS CATEGORY
	, dp.REGISTER_DATE
	, dc.REFERRAL_CODE
	, dc.MEDIA
	, dc.CAMPAIGN
	, dp.PARTNER_NAME AS MERCHANT_NAME
	, dp.ADDRESS AS MERCHANT_ADDRESS
	, dp.PHONE AS MERCHANT_PHONE
	, dp.PARTNER_ID AS VIRTUAL_ACCOUNT
	, ac.CREDIT_TRANS
	, ac.CREDIT_AMOUNT
	, ac.T_VALUE_DATE
	, ac.T_DATE_TIME
	, de.DEPO_PROD_CODE
--
	FROM ac 
	JOIN ft 
		ON ac.CREDIT_TRANS = ft.FT_NO
	RIGHT JOIN dp 
		ON ft.MERCHANT_ID = dp.PARTNER_ID
	LEFT JOIN de 
		ON dp.ACCOUNT = de.ACCOUNT_NO
	LEFT JOIN dc 
		ON dp.CIF = dc.CUSTOMER_ID;

--Báo cáo 1c 
		
--CASA CRB 
--Bảng VIEW
 DROP TABLE PPTTT.TBL_CRB_CASA;
 CREATE TABLE PPTTT.tbl_crb_casa AS 
 WITH W_DATA_DATE_FULL AS (
    SELECT DATA_DT AS HOLIDAY_DT,
        CASE WHEN HOLIDAY=1 THEN LEAD (rn) ignore nulls OVER (ORDER BY DATA_DT DESC) ELSE DATA_DT  END AS DATA_DT,
        DATA_DATE_DT HOLIDAY_DATE_DT,
        TO_DATE(CASE WHEN HOLIDAY=1 THEN LEAD (rn)  ignore nulls  OVER(ORDER BY DATA_DT DESC)  ELSE DATA_DT  END,'YYYYMMDD') AS DATA_DATE_DT,
        CASE WHEN a.HOLIDAY =0 THEN 'WORKING' ELSE 'HOLIDAY' END BANG
        FROM (
            SELECT a.*, CASE WHEN HOLIDAY =0 THEN DATA_DT  ELSE NULL  END rn
            FROM TCIMPORT.DIM_CALENDAR_DATE a        
            ORDER BY 1 DESC
        )a 
        ORDER BY 1 DESC
    )
SELECT a."TIEUKHOAN", a."CUSTOMER_ID",a."DATE_COB",a."CDR_DT_ID", a."NOITE",
W.HOLIDAY_DATE_DT as DATA_DATE FROM (
SELECT 
  "FACT_CRB"."NOITE" , "FACT_CRB"."TIEUKHOAN", 	
  "FACT_CRB"."CUSTOMER_ID" AS "CUSTOMER_ID",
  "FACT_CRB"."DATE_COB" AS "DATE_COB",
  TO_CHAR("FACT_CRB"."DATE_COB",'YYYYMMDD') AS "CDR_DT_ID"
FROM "TCIMPORT"."FACT_CRB" "FACT_CRB"
WHERE 
"FACT_CRB".GL = '4211'
AND ("FACT_CRB".DATE_COB BETWEEN TRUNC(ADD_MONTHS(SYSDATE, -2), 'MM') /*lay ngay dau thang CUA 3 THANG TRUOC*/
		AND LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -1)))
) a LEFT JOIN W_DATA_DATE_FULL W ON a.CDR_DT_ID = W.DATA_DT;

-----
WITH ac AS 
(SELECT 
	to_char(trunc(sysdate),'yyyymmdd') AS DATA_DATE
	, ac.DATE_COB
	, ac.PRODUCT_CATEGORY AS CATEGORY
	, ac.TRANSACTION_NO as DEBIT_TRANS
	, substr(ac.TRANSACTION_NO, 1, instr(ac.TRANSACTION_NO, '\') -1) AS DEBIT_TRANS1 --'
	, ac.AMOUNT_LCY AS DEBIT_AMOUNT
	, ac.T_VALUE_DATE
	, ac.T_DATE_TIME
	, ac.AC_KEY
	, ft.MERCHANT_ID
	FROM TCIMPORT.FACT_ACCT_ENTRY ac 
	JOIN TCIMPORT.FACT_FUND_TRANS ft 
		ON 
		CASE WHEN 
		substr(ac.TRANSACTION_NO, 1, instr(ac.TRANSACTION_NO, '\') -1) IS NULL --'
		THEN ac.TRANSACTION_NO 
		WHEN substr(ac.TRANSACTION_NO, 1, instr(ac.TRANSACTION_NO, '\') -1) IS NOT NULL --'
		THEN substr(ac.TRANSACTION_NO, 1, instr(ac.TRANSACTION_NO, '\') -1) --'
		ELSE NULL
		END
		= REGEXP_SUBSTR(ft.FT_NO,'[^;]+',1,1)
		WHERE 
			ac.CRF_TP = 'DEBIT'
			AND ac.AMOUNT_LCY < 0
			AND ((ac.PRODUCT_CATEGORY BETWEEN 1001 AND 1099) AND ac.PRODUCT_CATEGORY <> 1008)
			AND (ac.DATE_COB BETWEEN TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') /*lay ngay dau thang CUA 3 THANG TRUOC*/
			AND LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -1)))
			AND ac.GL_NUMBER LIKE '42%' 
			AND (ft.DATE_COB BETWEEN TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') /*lay ngay dau thang CUA 3 THANG TRUOC*/
			AND LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -1))))
, dp AS 
(SELECT 
	* 
	FROM TCIMPORT.DIM_PARTNER dp 
	WHERE 
		dp.PARTNER_ID LIKE 'SPC%' 
		AND (LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -1)) BETWEEN dp.EFF_FM_DT AND dp.EFF_TO_DT)
		AND (dp.REGISTER_DATE <= LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -1))))
--
, de AS 
(SELECT 
	* 
	FROM TCIMPORT.DIM_DEPOSIT de 
	WHERE 
		(to_char(LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -1)),'yyyy-mm-dd') 
		BETWEEN to_char(de.EFF_FROM_DATE,'yyyy-mm-dd') AND nvl(to_char(de.EFF_TO_DATE,'yyyy-mm-dd'),'2400-01-01'))
		AND (de.START_DATE <= LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -1))))
, dc AS
(SELECT 
	* 
	FROM tcimport.DIM_CUSTOMER dc 
	WHERE 
		(to_char(LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -1)),'yyyy-mm-dd') 
		BETWEEN to_char(dc.EFF_FROM_DATE,'yyyy-mm-dd') AND nvl(to_char(dc.EFF_TO_DATE,'yyyy-mm-dd'),'2400-01-01')))
, crb AS
(SELECT 
	* 
	FROM PPTTT.TBL_CRB_CASA crb 
	WHERE 
		(crb.DATA_DATE BETWEEN TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') /*lay ngay dau thang CUA 3 THANG TRUOC*/
		AND LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -1))))
SELECT 
	trunc(sysdate/*ALTER*/) AS DATA_DATE
	, ac.DATE_COB
	, dp.CIF AS CIF
	, dc.CUSTOMER_NAME AS FULL_NAME
	, dp.ACCOUNT AS ACCOUNT_NUMBER
	, dp.ACCOUNT_OPEN_DATE AS ACCOUNT_OPEN_DATE
	, ac.CATEGORY
	, dp.PHONE AS PHONE
	, dp.PARTNER_ID as VIRTUAL_ACCOUNT
	, ac.DEBIT_TRANS
	, ac.DEBIT_TRANS1
	, ac.DEBIT_AMOUNT
	, ac.T_VALUE_DATE
	, ac.T_DATE_TIME
	, crb.NOITE
	, crb.DATE_COB as CRB_DATE_COB
	, de.DEPO_PROD_CODE
	, dp.REGISTER_DATE
	FROM ac
----
	RIGHT JOIN  dp 
		ON ac.AC_KEY = dp.ACCOUNT
	LEFT JOIN de 
		ON dp.ACCOUNT = de.ACCOUNT_NO 
	LEFT JOIN  dc 
		ON dp.CIF = dc.CUSTOMER_ID
	LEFT JOIN crb 
		ON dp.ACCOUNT = crb.TIEUKHOAN ;
		

