WITH W_DATA_DATE_FULL AS (
    SELECT DATA_DT AS HOLIDAY_DT,
        CASE WHEN HOLIDAY=1 THEN LEAD (rn) ignore nulls OVER (ORDER BY DATA_DT DESC) ELSE DATA_DT  END AS DATA_DT,
        DATA_DATE_DT HOLIDAY_DATE_DT,
        TO_DATE(CASE WHEN HOLIDAY=1 THEN LEAD (rn)  ignore nulls  OVER(ORDER BY DATA_DT DESC)  ELSE DATA_DT  END,'YYYYMMDD') AS DATA_DATE_DT,
        CASE WHEN a.HOLIDAY =0 THEN 'WORKING' ELSE 'HOLIDAY' END BANG
        FROM (
            SELECT a.*, CASE WHEN HOLIDAY =0 THEN DATA_DT  ELSE NULL  END rn
            FROM TCIMPORT.DIM_CALENDAR_DATE a        
            ORDER BY 1 DESC
        )a 
        ORDER BY 1 DESC
    )
, flt_org AS 
(SELECT b."CONTRACT_NO", b."CUSTOMER_ID", b."DATE_COB", b."CDR_DT_ID", b."BRANCH_CODE",b."DATASOURCE",b."BALANCE_LCY_AMT",
W.HOLIDAY_DATE_DT as DATA_DATE FROM (
SELECT 
 "FACT_LOAN_T24"."DATE_COB",
 "FACT_LOAN_T24"."CONTRACT_NO",
 "FACT_LOAN_T24"."BRANCH_CODE",
 "FACT_LOAN_T24"."CUSTOMER_ID",
 "FACT_LOAN_T24"."DATASOURCE",
 "FACT_LOAN_T24"."BALANCE_LCY_AMT",
  TO_CHAR("FACT_LOAN_T24"."DATE_COB",'YYYYMMDD') AS "CDR_DT_ID"
FROM "TCIMPORT"."FACT_LOAN_T24" "FACT_LOAN_T24"
WHERE 
("FACT_LOAN_T24"."DATE_COB" BETWEEN TRUNC(sysdate-10/*ALTER-10*/) 
		AND trunc(sysdate-1/*ALTER-1*/))
) b LEFT JOIN W_DATA_DATE_FULL W ON b.CDR_DT_ID = W.DATA_DT)
, flt AS
	(SELECT 
	t_3.* 
	FROM flt_org t_3 
	LEFT OUTER JOIN (SELECT * FROM flt_org
	WHERE 
		DATA_DATE = trunc(sysdate-1/*ALTER-1*/)
		AND DATASOURCE = 'T24'
		AND SUBSTR(CONTRACT_NO,1,2)='LD'
		AND BALANCE_LCY_AMT = 0) t_2 
	ON t_3.CONTRACT_NO = t_2.CONTRACT_NO 
	WHERE 
		t_3.DATA_DATE = trunc(sysdate-2/*ALTER-2*/)
		AND t_3.DATASOURCE = 'T24'
		AND SUBSTR(t_3.CONTRACT_NO,1,2)='LD'
		AND t_2.CONTRACT_NO IS not NULL
		AND t_3.BALANCE_LCY_AMT <> 0)
, dlt AS 
	(SELECT 
		* 
		FROM TCIMPORT.DIM_LOAN_T24 dlt
		WHERE 
			(trunc(sysdate-2/*ALTER-2*/) BETWEEN EFF_FROM_DATE  AND nvl(EFF_TO_DATE,TO_DATE(24000101,'yyyymmdd')))
			AND SUBSTR(dlt.CONTRACT_NO,1,2)='LD')
, db AS 
	(SELECT 
		* 
		FROM TCIMPORT.DIM_BRANCH db 
		where 
			(trunc(sysdate-1/*ALTER-1*/) BETWEEN EFF_FROM_DATE  AND nvl(EFF_TO_DATE,TO_DATE(24000101,'yyyymmdd'))))
, dc AS 
	(SELECT 
		* 
		FROM TCIMPORT.DIM_CUSTOMER dc 
		where 
			(trunc(sysdate-1/*ALTER-1*/) BETWEEN EFF_FROM_DATE  AND nvl(EFF_TO_DATE,TO_DATE(24000101,'yyyymmdd'))))
SELECT DISTINCT DATA_DATE
	, DATE_COB 
	, ID 
	, BPM_DSBR_ID 
	, SAN_PHAM
	, MA_CN
	, TEN_CN 
	, KHOI 
	, CIF
	, TEN_KH 
	, NGAY_GN 
	, NGAY_TAT_TOAN_TT 
	, KY_HAN
	, EFF_FROM_DATE 
	, EFF_TO_DATE
	FROM (
		SELECT
			TRUNC(SYSDATE/*ALTER*/) AS DATA_DATE
			, flt.DATE_COB
			, flt.CONTRACT_NO AS ID
			, dlt.BPM_DSBR_ID 
			, dlt.LOAN_SUBPRODUCT_NAME SAN_PHAM
			, flt.BRANCH_CODE MA_CN 
			, db.BRANCH_NAME TEN_CN 
			, dc.CUSTGROUP_NAME AS KHOI 
			, flt.CUSTOMER_ID AS CIF
			, dc.CUSTOMER_NAME AS TEN_KH
			, dlt.START_DATE AS NGAY_GN
			, dlt.MATURITY_DATE AS NGAY_TAT_TOAN_TT 
			, dlt.TERM KY_HAN
			, dlt.EFF_FROM_DATE 
			, dlt.EFF_TO_DATE
		FROM flt 
		LEFT JOIN dlt 
			ON flt.CONTRACT_NO = dlt.CONTRACT_NO
		LEFT JOIN  db 
			ON flt.BRANCH_CODE = db.BRANCH_CODE
		LEFT JOIN dc 
			ON flt.CUSTOMER_ID = dc.CUSTOMER_ID);
			
-------
--MD 
WITH W_DATA_DATE_FULL AS (
    SELECT DATA_DT AS HOLIDAY_DT,
        CASE WHEN HOLIDAY=1 THEN LEAD (rn) ignore nulls OVER (ORDER BY DATA_DT DESC) ELSE DATA_DT  END AS DATA_DT,
        DATA_DATE_DT HOLIDAY_DATE_DT,
        TO_DATE(CASE WHEN HOLIDAY=1 THEN LEAD (rn)  ignore nulls  OVER(ORDER BY DATA_DT DESC)  ELSE DATA_DT  END,'YYYYMMDD') AS DATA_DATE_DT,
        CASE WHEN a.HOLIDAY =0 THEN 'WORKING' ELSE 'HOLIDAY' END BANG
        FROM (
            SELECT a.*, CASE WHEN HOLIDAY =0 THEN DATA_DT  ELSE NULL  END rn
            FROM TCIMPORT.DIM_CALENDAR_DATE a        
            ORDER BY 1 DESC
        )a 
        ORDER BY 1 DESC
    )
, ftf_org AS 
(SELECT b."TFMD_ID", b."DATE_COB", b."CDR_DT_ID", b."BRANCH_CODE",
W.HOLIDAY_DATE_DT as DATA_DATE FROM (
SELECT 
 "FACT_TRADE_FINANCE"."DATE_COB",
 "FACT_TRADE_FINANCE"."TFMD_ID",
 "FACT_TRADE_FINANCE"."BRANCH_CODE",
  TO_CHAR("FACT_TRADE_FINANCE"."DATE_COB",'YYYYMMDD') AS "CDR_DT_ID"
FROM "TCIMPORT"."FACT_TRADE_FINANCE" "FACT_TRADE_FINANCE"
WHERE 
("FACT_TRADE_FINANCE"."DATE_COB" BETWEEN TRUNC(sysdate-10/*ALTER-10*/) 
		AND trunc(sysdate-1/*ALTER-1*/))
) b LEFT JOIN W_DATA_DATE_FULL W ON b.CDR_DT_ID = W.DATA_DT)
, tf AS
	(SELECT 
		t_3.* 
		FROM ftf_org t_3 
		LEFT OUTER JOIN 
			(SELECT 
				TFMD_ID 
				FROM ftf_org
				WHERE 
				DATA_DATE = trunc(sysdate-1/*ALTER-1*/)
				AND SUBSTR(TFMD_ID,1,2)='MD') t_2 
		ON t_3.TFMD_ID = t_2.TFMD_ID 
		WHERE 
			t_3.DATA_DATE = trunc(sysdate-2/*ALTER-2*/)
			AND SUBSTR(t_3.TFMD_ID,1,2)='MD'
			AND t_2.TFMD_ID IS NULL)
, dtf AS 
	(SELECT 
		* 
		FROM TCIMPORT.DIM_TRADE_FINANCE dtf 
		WHERE 
			(trunc(sysdate-2/*ALTER-2*/) BETWEEN EFF_FROM_DATE  AND nvl(EFF_TO_DATE,TO_DATE(24000101,'yyyymmdd')))
			AND dtf.TFMD_ID LIKE 'MD%')
, db AS 
	(SELECT 
		* 
		FROM TCIMPORT.DIM_BRANCH db 
		where 
			(trunc(sysdate-1/*ALTER-1*/) BETWEEN EFF_FROM_DATE  AND nvl(EFF_TO_DATE,TO_DATE(24000101,'yyyymmdd'))))
, dc AS 
	(SELECT 
		* 
		FROM TCIMPORT.DIM_CUSTOMER dc 
		where 
			(trunc(sysdate-1/*ALTER-1*/) BETWEEN EFF_FROM_DATE  AND nvl(EFF_TO_DATE,TO_DATE(24000101,'yyyymmdd'))))
SELECT DISTINCT DATA_DATE
	, DATE_COB 
	, ID 
	, BPM_DSBR_ID 
	, SAN_PHAM
	, MA_CN
	, TEN_CN 
	, KHOI 
	, CIF
	, TEN_KH 
	, NGAY_GN 
	, NGAY_TAT_TOAN_TT 
	, KY_HAN
	, EFF_FROM_DATE 
	, EFF_TO_DATE
	FROM ( 
		SELECT
			TRUNC(SYSDATE/*ALTER*/) AS DATA_DATE
			, tf.DATE_COB 
			, tf.TFMD_ID AS ID
			, dtf.BPM_DSBR_ID 
			, dtf.LC_TYPE_NAME AS SAN_PHAM
			, tf.BRANCH_CODE AS MA_CN 
			, db.BRANCH_NAME AS TEN_CN 
			, dc.CUSTGROUP_NAME AS KHOI 
			, dtf.CUSTOMER_ID AS CIF
			, dc.CUSTOMER_NAME AS TEN_KH 
			, dtf.VALUE_DATE as NGAY_GN
			, dtf.CLOSING_DATE AS NGAY_TAT_TOAN_TT 
			, NULL AS KY_HAN
			, dtf.EFF_FROM_DATE 
			, dtf.EFF_TO_DATE
			FROM tf
			LEFT JOIN  dtf 
				ON tf.TFMD_ID = dtf.TFMD_ID
			LEFT JOIN db 
				ON tf.BRANCH_CODE = db.BRANCH_CODE
			LEFT JOIN dc 
				ON dtf.CUSTOMER_ID = dc.CUSTOMER_ID);